version: '3'

services:
  db:
    build: .
    container_name: devtranining-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=devtranining
